# Analysis

```{r, echo = FALSE, message = FALSE}
source(here::here("scripts/setup.R"))
```

regression Essai

```{r, echo = TRUE}
lm1 <- lm(dnb_results$TB_pct ~ dnb_results$without_pct + dnb_results$B_pct + dnb_results$AB_pct + dnb_results$without_pct)
summary(lm1)
```

cluster Essai

```{r, echo = TRUE}
dnb_pct_dep <- dnb_results %>%
  group_by(department, session) %>% 
  summarise(AB_pct_dep = mean(AB_pct, na.rm = TRUE),
            B_pct_dep = mean(B_pct, na.rm = TRUE),
            TB_pct_dep = mean(TB_pct, na.rm = TRUE),
            without_pct_dep = mean(without_pct, na.rm = TRUE),
            success_rate_pct_dep = mean(success_rate_pct, na.rm = TRUE))

pairs(dnb_pct_dep[2:6])

distance <- dist(dnb_pct_dep)

mydata.hclust <- hclust(distance)
plot(mydata.hclust)

```


Creation of the dataset used for the map

```{r, echo = TRUE}

result <- dnb_results %>% 
  select(department_fr, success_rate_pct) %>% 
  group_by(department_fr) %>% 
  summarise(success_rate = mean(success_rate_pct, na.rm = TRUE))

```

Join the map from ggplot and our new dataset

```{r, echo = TRUE}

result_map <- left_join(x = map[,-6], y = result)
```

plot

```{r, warning=FALSE, out.width='75%', out.height= '75%'}

p <-  ggplot() +
  geom_polygon(data = result_map, aes(long,lat, 
                            group = group, 
                            fill = success_rate, 
                            text = department_fr)) +
  geom_point(data = establishment_24, aes(x = longitude, y = latitude, text2= establishment), size = 0.5)+
  coord_map() +
  scale_fill_viridis(name = "Average sucess rate")+
  labs(x = "", 
       y = "", 
       title = "Average success rate, 2006-2021") +
  map_theme
  
ggplotly(p, tooltip = c("text2") )


#for other examples to change colours https://colinfay.me/mapping-the-french-second-round-results-with-r/
```

* Answers to the research questions
* Different methods considered
* Competing approaches
* Justifications